# Generated by Django 2.2.1 on 2019-05-24 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_auto_20190524_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('appname', models.CharField(max_length=50, verbose_name='Aplicación')),
                ('module', models.CharField(max_length=50, verbose_name='Módulo')),
                ('line', models.IntegerField(default=0, verbose_name='Linea')),
                ('error_type', models.CharField(blank=True, max_length=50, verbose_name='Tipo de error')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
